(function(g){var window=this;var hAa=function(a,b,c,d){var e=b.oc();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.rd(c,d?d:"mqdefault.jpg");var k=b instanceof g.VN?g.FV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.pQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.VN?b.za:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Qn(c),is_live:m,is_list:l,
is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.rQ&&(c.playlist_length=b.getLength());a.update(c)},n5=function(a,b){g.UH.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},o5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.V("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.V("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",U:{"aria-label":"{{watch}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",U:c,J:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.V("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.W.call(this,b);this.A=null;b=this.ua["ytp-upnext-cancel"];this.A=new g.W({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":g.V("YTP_AUTOPLAY_CANCEL")},J:[g.V("YTP_CANCEL")]});g.L(this,this.A);this.A.T("click",this.WO,this);this.A.va(b);this.l=a;this.I=this.ua["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Wt(this.gn,5E3,this);g.L(this,this.F);this.H=0;this.O(this.ua["ytp-upnext-autoplay-icon"],"click",
this.fR);this.nB();this.O(a,"autonavvisibility",this.nB);this.O(a,"mdxnowautoplaying",this.tQ);this.O(a,"mdxautoplaycanceled",this.uQ);this.O(a,"mdxautoplayupnext",this.UD);3==this.l.Va()&&(a=(a=g.SU(g.NU(this.l)))?a.jI():null)&&this.UD(a)},iAa=function(a,b){a.B=b;
hAa(a,b,g.Y(a.l),"hqdefault.jpg")},p5=function(a,b){if(!a.o){g.UF("a11y-announce",g.V("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.eG();a.o=new g.Wt((0,g.z)(a.oq,a,b),25);a.oq(b);var c=b||g.Y(a.l).experiments.l("autoplay_time")||1E4;a.l.ra("onAutonavCoundownStarted",c)}g.rq(a.element,"ytp-upnext-autoplay-paused")},r5=function(a){q5(a);
a.H=g.eG();a.oq();g.T(a.element,"ytp-upnext-autoplay-paused")},q5=function(a){a.o&&(a.o.dispose(),a.o=null)},s5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.aV(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.oc(),a.gn(),a.C=new window.Notification(g.V("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.rd(c)}),a.D=a.O(a.C,"click",a.VQ),a.F.start())}q5(a);a.l.Qj(!1,b)},jAa=function(a){n5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.W({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",U:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.L(this,this.o);this.o.va(this.element);this.A=new g.h_(g.V("YTP_SUBSCRIBE"),null,g.V("YTP_UNSUBSCRIBE"),null,!0,!1,b.Xl,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.A);this.A.va(this.o.ua["html5-subscribe-button-container"]);this.hide()},
t5=function(a){var b=g.Y(a),c=g.OJ||g.$e?{style:"will-change: opacity"}:void 0,d=b.l&&!b.B,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",aa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",U:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",L:"ytp-videowall-still-info-author",
J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.V("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.V("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",aa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.V("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.l=a;this.o=null;this.T("click",this.B);this.T("keypress",this.C);g.Y(a).P&&(a=a.app.da,b=this.element,g.Na(a.g,b),g.Qa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Ve(this,(0,g.z)(a.D,a,b)))},u5=function(a){n5.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.P=!1;this.B=new g.DF(this);g.L(this,this.B);this.M=new g.Wt(g.Ea(g.T,this.element,"ytp-show-tiles"),0);g.L(this,this.M);var b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":g.V("YTP_PREVIOUS")},J:[g.voa()]});g.L(this,b);b.va(this.element);b.T("click",this.WM,this);this.N=new g.OH({G:"div",L:"ytp-endscreen-content"});g.L(this,this.N);this.N.va(this.element);b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":g.V("YTP_NEXT")},J:[g.woa()]});g.L(this,b);b.va(this.element);b.T("click",this.VM,this);this.o=new o5(a);g.L(this,this.o);g.lV(this.l,this.o.element,4);g.Y(a).experiments.g("new_autonav_styling")&&g.T(this.o.element,"ytp-new-autonav");this.hide()},v5=function(a){return g.mV(a.l)&&a.tq()&&!a.H},kAa=function(a){return(0,g.H)(a.suggestions,function(a){return g.XY(a)})},w5=function(a){var b=a.Bt();
b!=a.P&&(a.P=b,a.l.R("autonavvisibility"))},x5=function(a){g.rV.call(this,a);
g.QG({YTP_AUTOPLAY_CANCEL:"Avbryt autoavspillingen",YTP_AUTOPLAY_NEXT:"Spill av den neste videoen",YTP_AUTOPLAY_PAUSED_3:"Autoavspilling er satt p\u00e5 pause",YTP_CANCEL:"Avbryt",YTP_MIX:"Samleliste",YTP_PLAYLIST_UP_NEXT:"Neste",YTP_UNSUBSCRIBE:"Avslutt abonnementet"});this.l=null;this.o=new g.DF(this);g.L(this,this.o);this.A=g.Y(a);lAa(a)?this.l=new u5(this.g):this.A.da?this.l=new jAa(this.g):this.l=new n5(this.g);g.L(this,this.l);g.lV(this.g,this.l.element,4);this.FC();this.o.O(a,"videodatachange",
this.FC,this);this.o.O(a,"crn_endscreen",this.eL,this);this.o.O(a,"crx_endscreen",this.fL,this)},lAa=function(a){a=g.Y(a);
return a.kd&&!a.da};
g.p(n5,g.UH);n5.prototype.create=function(){this.created=!0};
n5.prototype.destroy=function(){this.created=!1};
n5.prototype.tq=function(){return!1};
n5.prototype.Bt=function(){return!1};g.p(o5,g.W);g.h=o5.prototype;g.h.gn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.nB=function(){g.TH(this,g.OU(this.l))};
g.h.VQ=function(){window.focus();this.gn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.oq=function(a){a=a||g.Y(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.eG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.l.Va()?s5(this,!0):this.o&&this.o.start()};
g.h.fR=function(a){!g.Md(this.A.element,g.sF(a))&&g.jX(a,this.l)&&s5(this)};
g.h.WO=function(){g.QU(this.l,!0)};
g.h.tQ=function(a){this.l.Va();this.show();p5(this,a)};
g.h.UD=function(a){this.l.Va();this.B&&this.B.oc().videoId==a.oc().videoId||iAa(this,a)};
g.h.uQ=function(){this.l.Va();q5(this);this.hide()};
g.h.V=function(){q5(this);this.gn();g.W.prototype.V.call(this)};g.p(jAa,n5);g.p(t5,g.W);t5.prototype.ek=function(){g.pV(this.l,this.element);var a=this.o.oc().videoId,b=this.o.getPlaylistId();g.g0(this.l.app,a,this.o.fe,b,void 0,void 0,void 0)};
t5.prototype.B=function(a){g.jX(a,this.l,this.A,this.o.fe||void 0)&&this.ek()};
t5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.xF(a)||(this.ek(),g.wF(a))}};g.p(u5,n5);g.h=u5.prototype;g.h.create=function(){n5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=kAa(a),this.D=a);this.Dg();this.B.O(this.l,"appresize",this.Dg);this.B.O(this.l,"onVideoAreaChange",this.Dg);this.B.O(this.l,"videodatachange",this.XM);this.B.O(this.l,"autonavchange",this.pA);this.B.O(this.l,"autonavcancel",this.UM);this.B.O(this.element,"transitionend",this.vS)};
g.h.destroy=function(){g.FF(this.B);g.Xe(this.A);this.A=[];this.C=null;n5.prototype.destroy.call(this);g.rq(this.element,"ytp-show-tiles");this.M.stop()};
g.h.tq=function(){return 1!=this.D.autonavState};
g.h.show=function(){n5.prototype.show.call(this);g.rq(this.element,"ytp-show-tiles");g.Y(this.l).g?g.Yt(this.M):this.M.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.QU(this.l,!1);var a=v5(this);g.mV(this.l)&&g.Y(this.l).experiments.g("ui_logging")&&g.aV(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.tq()?"enabled":"disabled"});a?(w5(this),2==this.D.autonavState?g.Y(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Di()?s5(this.o,!0):p5(this.o):3==this.D.autonavState&&
r5(this.o)):(g.QU(this.l,!0),w5(this))};
g.h.hide=function(){n5.prototype.hide.call(this);r5(this.o);w5(this)};
g.h.vS=function(a){g.sF(a)==this.element&&this.Dg()};
g.h.Dg=function(){if(this.C&&this.C.length){g.T(this.element,"ytp-endscreen-paginate");if(g.Y(this.K).experiments.g("web_player_endscreen_size_killswitch"))var a=g.Jh(this.element);else{a=g.dV(this.K);var b=g.hI(this.K);b&&(b=b.td()?48:32,a.width-=2*b)}var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,B=e<=k-2&&n>=q*m;if((q+
1)/r*d/c>c/(q/(r+1)*d)&&B)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(B)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Yc(a.width/m||1,1,1.21);n*=g.Yc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Ih(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});iAa(this.o,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",v5(this));w5(this);m+=4;
n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.Zc(q+this.F,l),0!=r){u=this.A[c];u||(u=new t5(this.l),this.A[c]=u,a.appendChild(u.element));B=Math.floor(n*k/e);var F=Math.floor(m*f/b),M=Math.floor(n*(k+r)/e)-B-4,ba=Math.floor(m*(f+r)/b)-F-4;g.xh(u.element,F,B);g.Ih(u.element,ba,M);g.oh(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==r);g.U(u.element,"ytp-videowall-still-large",2<r);r=
u;q=this.C[q];r.o=q;hAa(r,q,g.Y(r.l),g.pq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");u=q.fe;q=r.l;g.Y(q).P&&(q=q.app.da,r=r.element,u=u&&u.itct,B=r.getAttribute("data-visual-id"),g.Na(q.g,r),g.nV(q,"onLogServerVeCreated",{id:B,tracking_params:u}));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Fd(e.element),g.We(e);this.A.length=c}};
g.h.XM=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=kAa(a),this.D=a,this.Dg())};
g.h.VM=function(){this.F+=this.A.length;this.Dg()};
g.h.WM=function(){this.F-=this.A.length;this.Dg()};
g.h.lK=function(){return!!this.o.o};
g.h.pA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,q5(this.o),this.g&&this.Dg()):(this.I=!0,this.g&&v5(this)&&(2==a?p5(this.o):3==a&&r5(this.o)))};
g.h.UM=function(a){if(a){for(a=0;a<this.A.length;a++)g.qV(this.K,this.A[a].element,!0);this.pA(1)}else this.H=null,this.I=!1;this.Dg()};
g.h.Bt=function(){return this.g&&v5(this)};g.p(x5,g.rV);g.h=x5.prototype;g.h.Qz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!lAa(this.g)||b;a=g.nO(a,"ypc_module");var c=g.h0(this.g.app);return b&&!a&&!c};
g.h.Pz=function(){return this.l.Bt()};
g.h.hK=function(){return this.Pz()?this.l.lK():!1};
g.h.V=function(){g.jV(this.g,"endscreen");g.rV.prototype.V.call(this)};
g.h.load=function(){g.rV.prototype.load.call(this);this.l.show();g.Y(this.g).da&&.01>Math.random()&&g.aV(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.rV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.eL=function(a){this.Qz()&&(this.l.created||this.l.create(),"load"==a.ia&&this.load())};
g.h.fL=function(a){"load"==a.ia&&this.loaded&&this.unload()};
g.h.FC=function(){g.jV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.mQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.mQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.gV(this.g,[a,b])};g.cY.endscreen=x5;})(_yt_player);
